##################################################
# BrandPDF Pro Application Configuration
##################################################

# Application Info
app.name=BrandPDF Pro
app.version=1.1.0
app.title=BrandPDF Pro v1.0.0

# Window Settings
app.width=950
app.height=950

# Preview Settings
preview.width=400
preview.height=80

# Default PDF Settings
default.header.height=80
default.footer.height=80